feat: register a custom editor component named toggle Section
healthyregions/SDOHPlace pull request #350
Opened 2024-10-24 18:39 UTC by bodom0015

## Problem
DecapCMS allows us to create custom editor components to render complex Markdown

## Approach
* feat: create a custom editor component that will produce standard `<details>`/`<summary>` toggles as HTML

Example:
![Screenshot 2024-10-24 at 1 26 29 PM](https://github.com/user-attachments/assets/dae13448-be75-49ec-b3de-4ddc41e40fc9)

Which produces the following HTML:
```html
<details name="example"><summary>1. Access varies depending on where you are (origin)</summary><p>Imagine living in downtown Chicago, where it is easy to catch a bus or hop on the subway to get to work, visit friends, or run errands. If the transit system is well-connected, and stops are just a short walk from your home, this could make it convenient for you to rely on public transportation. Now, if someone lives in a small rural town where public transit might be limited to a few bus routes that only run a couple of times a day. The nearest bus stop could be several miles away, making it inconvenient to rely on public transportation. At the same time, some individuals may find it convenient to obtain services near their work or shopping locations, indicating that daily activity spaces other than residential locations can be more representative of origin in measuring public transit calculations. This highlights the importance of origin (location) in accessibility decision making.</p></details>
```

## How to Test
1. Navigate to `/admin/index.html`
2. Click on Guides on the left, and choose the "Public Transit Equity" guide from the list
    * You should see an Editor on the left, and a preview of the contents on the right
3. Ensure that the editor is set to "Rich-text" mode
4. Expand the "+" dropdown on the editor
    * You should see "Toggle Section" listed here - this is our newly-added component
5. Choose "Toggle Section" from the list
    * You should see a new widget named "Toggle Section" appear in the editor below
    * You should see that this widget has 3 separate inputs: `title`, `content`, `group`
6. Enter a value for `Title` - this will be the clickable header when the section is collapsed
7. Enter a value for `Content` - this will be Markdown that becomes the main content for when the section is expanded
8. (optional) Enter a value for `Group` - if specified, only a single section from the same group can be expanded at once
9. Change between the "Rich-text" and "Markdown" modes in the editor
    * You should see the widget is converted to its raw HTML format (see above) and then back again
10. Try to come up with weird edge cases that might break this widget
    * NOTE: The HTML form must be a produced as a single line, or else we have trouble detecting the end of one Toggle Section and the start of another

2024-10-25 15:26 UTC, mradamcox commented
Looking good so far! However, it seems like even though the Markdown widget is used for the content, it doesn't get rendered properly:

![image](https://github.com/user-attachments/assets/b80db00b-8026-4743-b8ca-8401cdd661e5)

Better behavior would either

1. (preferred) render markdown to HTML in the preview as well as in the final page (I didn't check the final page, but assume it isn't working there either), or
2. (alternative) replace the markdown widget for the content field with a plain text widget.

I'm assuming we can write raw HTML into this content regardless of what widget is used, so if that is the only way we can have complex content, like lists or images, then we should force the user to do that, and not provide a markdown widget that doesn't work.

2024-10-25 15:26 UTC, mradamcox requested changes
(see above comment)

2024-10-25 19:57 UTC, bodom0015 commented
Thank you for the feedback, @mradamcox!

Sorry, I had based this implementation off of the DecapCMS example "Collapsible Note":
https://decapcms.org/docs/custom-widgets/#registereditorcomponent

They specified the widget type as `markdown`, so I assumed this would handle Markdown appropriately by default 🤔 
Apparently this case needed some special care and we now use `marked` to parse the Markdown within the Toggle Section:
https://github.com/markedjs/marked

Gotchas involved that we're working around here:
* there must be a space before markdown content or else it will not render properly - I think I've added this in the background so the user shouldn't need to worry about it
* single-quoted attributes appeared to work best with the RemoteMDX version on `/guides/[slug]`, even though both single and double quotes are accepted by the editor in DecapCMS
* regex needed some special care to properly detect the end of the value of the `name` attribute - without this there were some errors parsing group name out of adjacent Toggle Sections
* This does NOT support nested Toggle Sections, even though the widget is offered in the sub-editor as well - after converting to Markdown and back, the sub-sub-editors will be lost, as there is it is not trivial to parse out these nested values using regex

Things that I should be well tested:
* Adding a Toggle Section via the button in the Editor
* Converting entire document back and forth in Rich-text vs Markdown this transformation works both ways
* Inserting Markdown values into the `content` of the Toggle Section
* Creating / Converting Toggle Sections both with and without `group` specified
* All of the above verified on the resulting `/guides/` view as well (rendered via RemoteMDX)

2024-10-28 18:05 UTC, mradamcox requested changes
Looking really good. Can you see about disabling the toggle section component in the nested markdown widget? https://github.com/decaporg/decap-cms/issues/3459. It would be good to know if it is possible in general, because we will likely end up with other custom components that we only want to have available in certain uses of the markdown widget.

2024-10-28 19:35 UTC, bodom0015 commented
@mradamcox yes, it looks like we were able to prevent the user from adding one Toggle Section with an existing Toggle Section :+1:

```json
          {
            name: 'content',
            label: 'Content',
            widget: 'markdown',
            // exclude toggle-section from being nested inside of another toggle-section
            editor_components: [ "image", "code-block" ],
            required: true
          },
```

Adding the `editor_components` property allows us to customize which buttons are offered under the `+` button in the sub-editor :tada:

2024-10-28 20:12 UTC, mradamcox commented
Ok, perfect, thanks for figuring that out. It will make it a lot easier to add custom editor components and only use them in certain instances of the markdown widget. One _final_ request for this PR: Could you add `cursor: pointer` style to the summary element, so that the toggle looks a little bit more like a button when you hover over it? After that, ready to merge!

2024-10-28 21:14 UTC, bodom0015 commented
@mradamcox awesome! I was able to add this style pretty easily into our rendered version of the CMS (e.g. `/guides/public-transit-equity`)

I didn't see an easy way to adjust this in the DecapCMS preview as well, but I can spend some time to look into that if it is important?

2024-10-28 21:27 UTC, mradamcox approved these changes
Looks good to me. As we get more familiar with this pattern we can probably drop a lot of these comments, but for now I think it's fine to retain them.

2024-10-28 21:27 UTC, merged